version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.hazelcast:hazelcast
    versions:
    - 4.1.1
    - 4.1.2
  - dependency-name: org.apache.ant:ant-testutil
    versions:
    - 1.10.9
  - dependency-name: org.apache.ant:ant
    versions:
    - 1.10.9
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
  - dependency-name: com.fasterxml.jackson.module:jackson-module-afterburner
    versions:
    - 2.12.1
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
